version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  typescript-lint:
    executor:
      name: node/default
      tag: '14.19.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint TypeScript
          command: npm run typescript-lint

  scss-lint:
    executor:
      name: node/default
      tag: '14.19.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint SCSS
          command: npm run scss-lint

  test:
    executor:
      name: node/default
      tag: '14.19.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID' >> $BASH_ENV
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            npm run test -- --coverage
            echo $CC_TEST_REPORTER_ID
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?

  build:
    executor:
      name: node/default
      tag: '14.19.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build Project
          command: npm run build

workflows:
  lint_test_and_build:
    jobs:
      - typescript-lint
      - scss-lint:
          requires:
            - typescript-lint
      - test:
          requires:
            - typescript-lint
            - scss-lint
      - build:
          requires:
            - typescript-lint
            - scss-lint
            - test
